### ISSUE TITLE
Add readme.md to github project

### ISSUE THREAD

**Issue by aryoda** [Android-Boot-Manager/droidboot_device_volla_yggdrasil#1]
Please add a short description with basic information like

- purpose of the project
- possible use cases
- how to build
- how to install
- status of development

I came from a link at https://www.kickstarter.com/projects/volla/volla-phone-designed-with-simplicity-and-security-in-mind/posts/2901919
and it just contained a "teaser" paragraph:

> In the context of our developer community an exciting project of „Luka" has progressed, that he started at the hackathon
> of last the Volla Community Days.
> On the Volla Phone it allows to choose between the start of two different operating systems, one of them installed on a fast SD card.
> This is not only exciting to try out an alternative operating system, but also to use a second one for use cases that need special security.

**Comment by luka177** [comment]
Hi.
It is cool to see someone is interested in this. Thanks for issue. Tomorrow this will be done.

**Comment by aryoda** [comment]
I am very interested in the use cases mentioned in the link above:

Use the SD card to
1. try out an alternative operating system without changing the installed one
2. boot a known-good (untampered) operating system for special security reasons (eg. message encryption/decryption)

**Comment by nift4** [comment]
Don't forget this is not ready to use yet.

**Comment by luka177** [comment]
@aryoda  check now

**Comment by aryoda** [comment]
Thanks a lot! I'll clone, make some mod proposals and send a PR

**Comment by aryoda** [comment]
What is

- lk ("lk-based bootloader)?
- BSP ("based on the source code of BSP")?

I want to add links and explain the abreviations when they are mentioned for the first time in the readme...

**Comment by nift4** [comment]
lk: https://github.com/littlekernel
BSP: MediaTek bootloader & Android variant

**Comment by nift4** [comment]
@nift4 (Test ignore)
