### ISSUE TITLE
Booting of different operating systems on the same mobile device

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [Android-Boot-Manager/droidboot_device_volla_yggdrasil#6]
The current readme says "This repo contains a lk-based bootlader for the Volla Phone to support dualbooting (booting of different operating systems on the same mobile device) from the internal device storage or an inserted (fast) SD card." 

Can you define the term 'or' here and be more specific? 

My goal would be to use Sailfishos from internal device storage as a daily driver and when needed Android or Ubuntu as a secondary OS from SD card. Is this scenario possible?

If not, is a fast SD card sufficient enough to deliver a good user experience to run one of those alternative systems?

Thank you.

**Comment by nift4** [comment]
Hi. I recommened you to join https://t.me/andbootmgr as it's a lot more direct.

> Can you define the term 'or' here and be more specific?

Android from the internal storage and UT/SFOS from the SD card.

> My goal would be to use Sailfishos from internal device storage as a daily driver and when needed Android or Ubuntu as a secondary OS from SD card. Is this scenario possible?

See above.

> If not, is a fast SD card sufficient enough to deliver a good user experience to run one of those alternative systems?

Testers and I feel no difference on a good card (Class10).
