### ISSUE TITLE
is also mt6739 supported?

### ISSUE THREAD

**Issue by decaduto** [Android-Boot-Manager/droidboot_device_volla_yggdrasil#7]

**Comment by luka177** [comment]
If you have your bootloader sources its easy to port.

**Comment by decaduto** [comment]
No, I haven't, the model is an alcatel 5033D, is a fairly simple mt6739 device,  for the mt6735 platform, which project I must choose in the 'Makefile'?

**Comment by luka177** [comment]
6739 and 6735 are not the same. Ah and even if you find lk with 6739 support you will have to somehow port lcm (display) driver to it.

**Comment by decaduto** [comment]
I know that, but online there isn't anywhere the mt6739 lk.

**Comment by luka177** [comment]
Well apperently even abm have one... https://github.com/Android-Boot-Manager/droidboot_device_planet_cosmocom/tree/4e157f7f3def69cc47e2c5c8fec5346feaea2a8c/platform/mt6739

**Comment by decaduto** [comment]
the project name I need to use for compiling it what is?

**Comment by luka177** [comment]
Create your target based on 39tv1_bsp

**Comment by decaduto** [comment]
fixed everything, thanks
