### ISSUE TITLE
broken mt6739 bootloader

### ISSUE THREAD

**Issue by decaduto** [Android-Boot-Manager/droidboot_device_volla_yggdrasil#8]
sorry again my friend, but when I try to build with `make k39tv1_bsp_1g`, I got the following error: "No rule for generating "/home/XXX/Video/droidboot_device_planet_cosmocom-4e157f7f3def69cc47e2c5c8fec5346feaea2a8c/../../../../../../kernel-4.4/drivers/misc/mediatek/dws/mt6771/k71v1_64_bsp.dws", necessary for "build-k39tv1_bsp_1g/inc/cust_kpd.h", are you aware if is possible to fix or if is broken the repository?

**Comment by luka177** [comment]
1st you cant build bootloader like that, you should use cross-compiler
2nd this leads you to kernel, so you should try getting file from there
3rd it says mt6771 investigate on that
4th why you open issues on this repo, it is obviously not releated.
5th you have higher chance ti get help in our telegram chat: https://t.me/andbootmgr
